# Use Node.js image
FROM node:20-alpine

# Set working directory inside container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Expose the port your frontend runs on
EXPOSE 5173

# Start the dev server
CMD ["npm", "run", "dev"]
